<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc9d703b46ca65c86d72a5aee70f9aef2
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Ddeboer\\Imap\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ddeboer\\Imap\\' => 
        array (
            0 => __DIR__ . '/..' . '/ddeboer/imap/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc9d703b46ca65c86d72a5aee70f9aef2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc9d703b46ca65c86d72a5aee70f9aef2::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
